apiVersion: cert-manager.io/v1
  
kind: Certificate
metadata:
  name: hfconsulting-dev-tls
spec:
  secretName: hfconsulting-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hfconsulting.dev
  dnsNames:
    - hfconsulting.dev
    - www.hfconsulting.dev
  